version: "3.9"

services:
  backend:
    build:
      context: ../backend
    env_file:
      - ../.env        # contains PG_* to Neon and REDIS_URL to Upstash
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

networks:
  default:
    driver: bridge
