services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bookscanner
      POSTGRES_USER: bookscanner
      POSTGRES_PASSWORD: bookscanner
    ports: ["5433:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookscanner -d bookscanner"]
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - redisdata:/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata:
  redisdata:
