"""init tables

Revision ID: fc8368b6c7dd
Revises: 93a2504c2208
Create Date: 2025-09-05 18:57:19.059431

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fc8368b6c7dd"
down_revision: Union[str, None] = "93a2504c2208"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
